openapi: "3.0.0"
info:
  #include: ./info.yaml
servers:
  - url: https://petstore.swagger.io/api
paths:
  /pets:
    get:
      #include: ./paths/pets/get.yaml
    post:
      #include: ./paths/pets/post.yaml
  /pets/{id}:
    get:
      #include: ./paths/pets/{id}/get.yaml
    delete:
      #include: ./paths/pets/{id}/delete.yaml
components:
  schemas:
    Pet:
      #include: ./components/schemas/Pet.yaml
    NewPet:
      #include: components/schemas/NewPet.yaml
    Error:
      #include:./components/schemas/Error.yaml
