openapi: "3.0.0"
info:
  #include: ./info.yaml
servers:
  - url: https://petstore.swagger.io/api
paths:
  /pets:
    #include: ./paths/pets.yaml
  /pets/{id}:
    #include: ./paths/pets-id.yaml
components:
  schemas:
    Pet:
      #include: ./components/schemas/Pet.yaml
    NewPet:
      #include: components/schemas/NewPet.yaml
    Error:
      #include:./components/schemas/Error.yaml
